import type { User } from './types';

export const getMockUsers = (): User[] => [
  {
    id: '1',
    username: 'admin',
    email: 'admin@lab.local',
    roles: [
      {
        id: 'admin-role-id',
        name: 'Admin',
        isAdmin: true,
        canCreateServer: true,
      },
    ],
    firstName: 'Marie',
    lastName: 'Curie',
    active: true,
    isTwoFactorEnabled: true,
    createdAt: new Date('2023-01-01').toISOString(),
    updatedAt: new Date('2023-01-02').toISOString(),
  },
  {
    id: '2',
    username: 'techlab',
    email: 'tech@lab.local',
    roles: [
      {
        id: 'tech-role-id',
        name: 'Technicien',
        isAdmin: false,
        canCreateServer: true,
      },
    ],
    firstName: 'Jeanne',
    lastName: 'Dupont',
    active: true,
    isTwoFactorEnabled: false,
    createdAt: new Date('2023-02-01').toISOString(),
    updatedAt: new Date('2023-02-02').toISOString(),
  },
  {
    id: '3',
    username: 'invite',
    email: 'guest@lab.local',
    roles: [
      {
        id: 'guest-role-id',
        name: 'Invité',
        isAdmin: false,
        canCreateServer: false,
      },
    ],
    firstName: 'Jean',
    lastName: 'Dupont',
    active: false,
    isTwoFactorEnabled: false,
    createdAt: new Date('2023-03-01').toISOString(),
    updatedAt: new Date('2023-03-02').toISOString(),
  },
  {
    id: '4',
    username: 'ronan',
    email: 'ronan@lab.local',
    roles: [
      {
        id: 'guest-role-id',
        name: 'Invité',
        isAdmin: false,
        canCreateServer: false,
      },
      {
        id: 'tech-role-id',
        name: 'Technicien',
        isAdmin: false,
        canCreateServer: true,
      },
    ],
    firstName: 'Ronan',
    lastName: 'Le Goff',
    active: true,
    isTwoFactorEnabled: true,
    createdAt: new Date('2023-04-01').toISOString(),
    updatedAt: new Date('2023-04-02').toISOString(),
  },
  {
    id: '5',
    username: 'james',
    email: 'james@lab.local',
    roles: [
      {
        id: 'guest-role-id',
        name: 'Invité',
        isAdmin: false,
        canCreateServer: false,
      },
    ],
    firstName: 'James',
    lastName: 'Bond',
    active: false,
    isTwoFactorEnabled: true,
    createdAt: new Date('2023-05-01').toISOString(),
    updatedAt: new Date('2023-05-02').toISOString(),
  },
  {
    id: '6',
    username: 'charles',
    email: 'charles@lab.local',
    roles: [],
    firstName: 'Charles',
    lastName: 'Darwin',
    active: false,
    isTwoFactorEnabled: false,
    createdAt: new Date('2023-06-01').toISOString(),
    updatedAt: new Date('2023-06-02').toISOString(),
  },
];
